//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedtrainVives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGebruiker
    {
        public string GebruikersID { get; set; }
        public string Voornaam { get; set; }
        public string Naam { get; set; }
        public string Emailadres { get; set; }
        public string Wachtwoord { get; set; }
    }
}
