//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedtrainVives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHotel()
        {
            this.tblProduct = new HashSet<tblProduct>();
        }
    
        public int HotelID { get; set; }
        public int StadID { get; set; }
        public double PrijsPerOvernachting { get; set; }
        public string Naam { get; set; }
        public string Adres { get; set; }
        public string HotelFoto { get; set; }
    
        public virtual tblStad tblStad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProduct { get; set; }
    }
}
