//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedtrainVives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblBestellijn = new HashSet<tblBestellijn>();
            this.tblWinkelmandlijn = new HashSet<tblWinkelmandlijn>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> TrajectID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<byte> Treinklasse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBestellijn> tblBestellijn { get; set; }
        public virtual tblHotel tblHotel { get; set; }
        public virtual tblTraject tblTraject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWinkelmandlijn> tblWinkelmandlijn { get; set; }
    }
}
