//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedtrainVives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTraject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTraject()
        {
            this.tblProduct = new HashSet<tblProduct>();
            this.tblTussenlocatie = new HashSet<tblTussenlocatie>();
        }
    
        public int TrajectID { get; set; }
        public int Vertrek { get; set; }
        public int Aankomst { get; set; }
        public System.TimeSpan Tijdsstip { get; set; }
        public System.TimeSpan Reistijd { get; set; }
        public int BusinessPlaatsen { get; set; }
        public int EconomicPlaatsen { get; set; }
        public double BusinessPrijs { get; set; }
        public double EconomicPrijs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProduct { get; set; }
        public virtual tblStad tblStad { get; set; }
        public virtual tblStad tblStad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTussenlocatie> tblTussenlocatie { get; set; }
    }
}
