//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedtrainVives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTussenlocatie
    {
        public int TrajectID { get; set; }
        public int Volgnummer { get; set; }
        public string Naam { get; set; }
    
        public virtual tblTraject tblTraject { get; set; }
    }
}
