//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace speedtrainVives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWinkelmandlijn
    {
        public int WinkelmandlijnID { get; set; }
        public string GebruikersID { get; set; }
        public int ProductID { get; set; }
        public string Naam { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
